name: ViveCraftFeatures
version: '1.1'
main: ru.deelter.vr.viveCraftFeatures.ViveCraftFeatures
api-version: '1.21'
authors: [ DeelTer ]
depend: [ Vivecraft-Spigot-Extension ]
commands:
  scale:
    description: "Set player scale (0-100). 0 resets to default."
    usage: "/scale <0-100>"
    permission: vivecraftfeatures.scale